window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t734_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var coverBlock=document.querySelector('.t830');if(coverBlock){var slidesWrapper=rec.querySelector('.t-slds__items-wrapper');if(slidesWrapper&&slidesWrapper.classList.contains('t-slds_animated-none')){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}else{setTimeout(function(){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})},500)}}else{t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}
var currentCoverBlock=rec.querySelector('.t734');if(currentCoverBlock){currentCoverBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}}
function t686_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t686');if(!container)return;t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)});setTimeout(function(){t686_setHeight(recId)},100);window.addEventListener('resize',t_throttle(function(){t686_setHeight(recId)}));container.addEventListener('displayChanged',function(){t686_setHeight(recId)})}
function t686_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var wrapper=rec.querySelector('.t686');if(!wrapper)return;var col=rec.querySelector('.t-card__col');var ratio=wrapper.getAttribute('data-tile-ratio');if(!col)return;var container=rec.querySelector('.t686__container');var colStyle=getComputedStyle(col,null);var colPaddingLeft=parseInt(colStyle.paddingLeft)||0;var colPaddingRight=parseInt(colStyle.paddingRight)||0;var colHeight=(col.clientWidth-(colPaddingLeft+colPaddingRight))*+ratio;var maxHeight=0;var columnsInRow=Number(container.getAttribute('data-columns-in-row'));if(columnsInRow===0||columnsInRow===''){columnsInRow=1}
var allTables=Array.prototype.slice.call(rec.querySelectorAll('.t686__table'));var rowsArray=[];for(var i=0;i<allTables.length;i+=columnsInRow){rowsArray.push(allTables.slice(i,i+columnsInRow))}
for(var i=0;i<rowsArray.length;i++){var tables=rowsArray[i];for(var j=0;j<tables.length;j++){var table=tables[j];var textWrap=table.querySelector('.t686__textwrapper');var textWrapHeight=0;if(textWrap){textWrapHeight=textWrap.offsetHeight}
var cell=table.querySelector('.t686__cell');if(cell.classList.contains('t686__button-bottom')){var button=table.querySelector('.t686__button-container');if(button){textWrapHeight+=button.offsetHeight}}
if(textWrapHeight>maxHeight)maxHeight=textWrapHeight}
if(window.innerWidth>=960){if(maxHeight>colHeight){for(var j=0;j<tables.length;j++){var table=tables[j];table.style.height=maxHeight+'px';table.style.minHeight='auto'}}else{for(var j=0;j<tables.length;j++){var table=tables[j];table.style.height=colHeight+'px';table.style.minHeight='auto'}}}else{for(var j=0;j<tables.length;j++){var table=tables[j];table.style.height=null;table.style.minHeight=colHeight+'px'}}
if(!!document.documentMode){var bgs=[];var overlays=[];for(var tableIndex=0;tableIndex<tables.length;tableIndex++){bgs.push(tables[tableIndex].querySelector('.t686__bg'));overlays.push(tables[tableIndex].querySelector('.t686__overlay'))}
var tableHeight=parseInt(tables[0].style.height);for(var j=0;j<bgs.length;j++){bgs[j].style.height=tableHeight+'px'}
for(var j=0;j<overlays.length;j++){overlays[j].style.height=tableHeight+'px'}}}}
function t486_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var textWrapper=rec.querySelector('.t486__textwrapper');if(!textWrapper)return;var images=rec.querySelectorAll('.t486__blockimg');var imageContainer=rec.querySelector('.t486__imgcontainer');var imageHeight=images[0].clientWidth;if(window.innerWidth>980){for(var i=0;i<images.length;i++){images[i].style.height=imageHeight+'px'}
textWrapper.style.height=imageContainer.clientWidth+'px'}else{var imageStyle=getComputedStyle(images[0],null);var imagePaddingLeft=parseInt(imageStyle.paddingLeft)||0;var imagePaddingRight=parseInt(imageStyle.paddingRight)||0;var imageWidth=images[0].clientWidth-(imagePaddingLeft+imagePaddingRight);for(var i=0;i<images.length;i++){images[i].style.height=imageWidth+'px'}
textWrapper.style.height='auto'}}
function t802_insta_init(recId,instaUser){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t802');if(!container)return;var projectId=document.getElementById('allrecords').getAttribute('data-tilda-project-id');t802_insta_loadflow(recId,projectId,instaUser)}
function t802_insta_loadflow(recId,projectId,instaUser){var url='https://insta.tildacdn.com/fish/0.json';if(instaUser){url='https://insta.tildacdn.com/json/project'+projectId+'_'+instaUser+'.json'}
var xhr=new XMLHttpRequest();xhr.open('GET',url,!0);xhr.onreadystatechange=function(){if(xhr.readyState===4){if(xhr.status>=200&&xhr.status<400){var data=xhr.responseText;if(data){try{var objData=JSON.parse(data)}catch(error){console.log('Error. insta flow json not object');console.log(data)}
if(typeof objData==='object'){t802_insta_draw(recId,objData)}}}else{console.log('Error load instgram flow')}}};xhr.send()}
function t802_insta_draw(recId,objData){if(objData&&objData.photos&&objData.photos.length===0)return;var rec=document.getElementById('rec'+recId);if(!rec)return;var allImgWrappersNum=rec.querySelectorAll('.t802__imgwrapper_empty').length;for(var i=0;i<allImgWrappersNum;i++){if(objData.photos[i]){t802_insta_drawItem(recId,objData.username,objData.photos[i],i)}else{var empty=rec.querySelector('.t802__imgwrapper_empty');if(empty)empty.remove()}}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t802_insta_drawItem(recId,userName,photo,counter){var rec=document.querySelector('#rec'+recId);if(!rec)return;var empty=rec.querySelector('.t802__imgwrapper_empty');var isZoomable=rec.querySelector('.t802__container').getAttribute('data-zoom');if(empty){empty.classList.remove('t802__imgwrapper_empty');var main=empty.parentNode;var imageWrapper=document.createElement('div');imageWrapper.classList.add('t802__bgimg');if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){imageWrapper.classList.add('t-bgimg');imageWrapper.setAttribute('data-original',photo.url)}else{imageWrapper.style.backgroundImage='url('+photo.url+')'}
if(!isZoomable){var tagA=document.createElement('a');tagA.href=photo.link;tagA.target='_blank';empty.appendChild(imageWrapper);tagA.appendChild(empty);main.appendChild(tagA)}else{imageWrapper.setAttribute('data-zoomable','yes');imageWrapper.setAttribute('data-zoom-target',counter);imageWrapper.setAttribute('data-img-zoom-url',photo.url);if(photo.text){imageWrapper.setAttribute('data-img-zoom-descr',photo.text)}
imageWrapper.classList.add('t-zoomable');empty.appendChild(imageWrapper);main.appendChild(empty)}
var hover=empty.querySelector('.t802__hover-wrapper');if(hover&&window.isMobile===!1){var text=t802_insta_cropText(recId,'@'+userName+': '+photo.text);var divHover=document.createElement('div');var divText=document.createElement('div');divHover.classList.add('t802__hover-filter');divText.classList.add('t802__text','t-text','t-descr_xxs');divText.innerHTML=text;hover.appendChild(divHover);hover.appendChild(divText)}}}
function t802_insta_cropText(recId,text){var rec=document.getElementById('rec'+recId);var colsInLine=rec.querySelector('[data-cols-in-line]').getAttribute('data-cols-in-line');var maxLength=130;if(colsInLine==6){maxLength=90}
if(text.length>maxLength){text=text.substring(0,maxLength);text=text.substring(0,Math.min(maxLength,text.lastIndexOf(' ')));text+=' ...'}
return text}
function t281_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t281');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var hrefs=rec.querySelectorAll('a[href*="#"]');var popup=rec.querySelector('.t-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t281_showPopup(recId);t281_resizePopup(recId);t281__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t281__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t281_closePopup()});popupCloseBtn.addEventListener('click',t281_closePopup);for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||(url.substring(0,7)!='#price:'&&url.substring(0,7)!='#order:')){t281_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t281_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t281_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t281_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t281');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t281__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t281_lockScroll()},500)}
document.addEventListener('keydown',t281_escClosePopup)}
function t281_escClosePopup(event){if(event.key==='Escape')t281_closePopup()}
function t281_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t281__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t281_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t281_escClosePopup)}
function t281_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t281__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t365_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t365');if(!container)return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAnalitics=popup.getAttribute('data-track-popup');var popupCookieExist=popup.getAttribute('data-cookies-exist');var cookie='';var text=rec.querySelector('.t365__text');var popupCloseBtn=popup.querySelector('.t-popup__close');rec.setAttribute('data-animationappear','off');rec.style.opacity='1';if(popupCookieExist==='yes'){cookie=t365_readCookie('t365closefb')}else{cookie=t365_readCookie('')}
if(popupTooltipHook&&cookie!=='yes'){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});var hrefs=document.querySelectorAll('a[href="'+popupTooltipHook+'"]');for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(event){t365_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});event.preventDefault();if(popupAnalitics){var virtTitle=popupTooltipHook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(popupAnalitics,virtTitle)}});hrefs[i].addEventListener('keydown',function(event){if(event.keyCode===13){if(!window.isMobile)this.classList.add('t-popup__triggered-btn')}})}}
popup.addEventListener('click',function(event){if(event.target===this)t365_closePopup()});if(text){text.addEventListener('click',function(){t365_closePopup();t365_createCookie('t365closefb','yes',30)})}
popupCloseBtn.addEventListener('click',t365_closePopup)}
function t365_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t365');if(!container)return;var popup=rec.querySelector('.t-popup');var hrefs=rec.querySelectorAll('a[href*="#"]');var popupVK=document.getElementById('vk_groups_'+recId);if(popupVK&&popupVK.style.height==='0px'){popupVK.style.height='250px';var iframe=popupVK.querySelector('iframe');if(iframe)iframe.style.height='250px'}
t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t-body_popupshowed');for(var i=0;i<hrefs.length;i++){hrefs[i].removeEventListener('click',t365_hrefClickEvent);hrefs[i].addEventListener('click',t365_hrefClickEvent)}
document.addEventListener('keydown',t365_escClosePopup)}
function t365_hrefClickEvent(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t364_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t-body_popupshowed')},300)}}}
function t365_escClosePopup(event){if(event.key==='Escape')t365_closePopup()}
function t365_closePopup(){var popupAll=document.querySelectorAll('.t-popup');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t365_escClosePopup)}
function t365_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t365_createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires='; expires='+date.toGMTString()}else{var expires=''}
document.cookie=name+'='+value+expires+'; path=/'}
function t365_readCookie(name){var nameEQ=name+'=';var arrCookie=document.cookie.split(';');for(var i=0;i<arrCookie.length;i++){var cookie=arrCookie[i];while(cookie.charAt(0)==' '){cookie=cookie.substring(1,cookie.length)}
if(cookie.indexOf(nameEQ)==0){return cookie.substring(nameEQ.length,cookie.length)}}
return null}
function t451_initMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var burgerList=rec.querySelectorAll('.t451 .t-menuburger');var menu=rec.querySelector('.t451m');var menuBlock=rec.querySelector('.t451');var overlay=rec.querySelector('.t451m__overlay');var links=rec.querySelectorAll('.t-menu__link-item');Array.prototype.forEach.call(burgerList,function(burger){burger.addEventListener('click',function(e){e.preventDefault();t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu)})});if(menu){menu.click(function(e){t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu);e.preventDefault()})}
if(menuBlock){menuBlock.addEventListener('clickedAnchorInTooltipMenu',function(){t451_closeMenu(menu,overlay)})}
rec.addEventListener('click',function(e){if(window.innerWidth>980)return;var submenuClassList=['.t451__link-item_submenu','.t966__tm-link','.t978__tm-link','.t978__menu-link_hook'];var isContainsSubmenuClass=submenuClassList.some(function(className){return e.target.closest(className)});if(!isContainsSubmenuClass)return;setTimeout(function(){t451_checkSize(menu)},100)});window.addEventListener('resize',function(){t451_checkSize(menu)});menu.addEventListener('menuOverflow',function(){t451_checkSize(menu)});var navLinks=rec.querySelectorAll('.t451 a.t-menu__link-item[href*="#"], .t451 a.t-menusub__link-item[href*="#"]');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length>0){t_onFuncLoad('t_menu__updateActiveLinks',function(){t_menu__updateActiveLinks(navLinks,'.t451')})}
t_onFuncLoad('t_menu__highlightActiveLinks',function(){t_menu__highlightActiveLinks('.t451m__menu a')});document.addEventListener('click',function(e){if(e.target.closest('.t451m__overlay, .t451m__close, a[href*="#"]:not(.tooltipstered):not(.t794__tm-link):not(.t978__tm-link):not(.t966__tm-link):not(.t978__menu-link_hook):not(.t-menuwidgeticons__link_wishlist):not(.t-menuwidgeticons__link_cart)')){t451_closeMenu(menu,overlay)}});document.addEventListener('keydown',function(e){if(e.keyCode===27){t451_closeMenu(menu,overlay)}})}
function t451_showMenu(menu,overlay){if(!menu)return;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t451__body_menushowed');menu.classList.add('t451m__menu_show');if(overlay)overlay.classList.add('t451m__menu_show')}
function t451_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t451__body_menushowed');if(menu)menu.classList.remove('t451m__menu_show');if(overlay)overlay.classList.remove('t451m__menu_show')}
function t451_checkSize(menu){if(!menu)return;var menuTop=menu.querySelector('.t451m__top');var menuRight=menu.querySelector('.t451m__rightside');var menuContainer=menu.querySelector('.t451m__container');var menuTopHeight=menuTop?menuTop.offsetHeight:0;var menuRightHeight=menuRight?menuRight.offsetHeight:0;var windowPadding=80;if(menuTopHeight+menuRightHeight+windowPadding>window.innerHeight){menu.classList.add('t451m__overflowed');if(menuContainer)menuContainer.style.height='auto'}else{menu.classList.remove('t451m__overflowed');if(menuContainer)menuContainer.style.height=''}}
function t451_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t451__panel'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';if(burgerAppearOffset)burgerAppearOffset=t451_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t451__beforeready')){burger.classList.remove('t451__beforeready')}}else{burger.classList.add('t451__beforeready')}}
function t451_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string,10)/100)))}
return parseInt(string,10)}
function t985_init(recid,searchVariants){var rec=document.querySelector('#rec'+recid);if(!rec)return;if(searchVariants.length>0){t985_addSearchVariants(recid,searchVariants)}
var searchWidgetIcon=rec.querySelectorAll('.t985__search-widget-icon');Array.prototype.forEach.call(searchWidgetIcon,function(widgetIcon){widgetIcon.addEventListener('click',function(){t985_showSearch(rec)})});var closeIcon=rec.querySelector('.t985__close-icon');if(closeIcon){closeIcon.addEventListener('click',function(){t985_hideSearch(rec)})}
var overlay=rec.querySelector('.t985__overlay');if(overlay){overlay.addEventListener('click',function(event){var target=event.target;var parentTarget=target.parentElement;if(!target.classList.contains('.t985__widgetheader')&&!parentTarget.classList.contains('.t985__widgetheader')){t985_hideSearch(rec)}})}}
function t985_addSearchVariants(recid,searchVariants){var rec=document.querySelector('#rec'+recid);if(!rec)return;var container=rec.querySelector('.t985__searchvariants');var cleanVariants=searchVariants.replace(/(<([^>]+)>)/gi,'')
var searchArray=cleanVariants.split(',');Array.prototype.forEach.call(searchArray,function(variant){container.innerHTML+='<div class="t985__searchvariant t-text t-text_xs">'+variant+'</div>'})}
function t985_showSearch(rec){rec.querySelector('.t985__overlay').style.display='block';rec.querySelector('.t985__search-widget-icon').style.display='none'}
function t985_hideSearch(rec){rec.querySelector('.t985__overlay').style.display='none';rec.querySelector('.t985__search-widget-icon').style.display='block'}
function t658_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;rec.setAttribute('data-animationappear','off');rec.classList.remove('r_hidden');rec.classList.remove('r_anim');var wrapperBlock=rec.querySelector('.t658');var confirmPopup=rec.querySelector('.t658__popup_confirm');var denyPopup=rec.querySelector('.t658__popup_deny');var yesButton=rec.querySelector('.t658__btn_yes');var noButton=rec.querySelector('.t658__btn_no');var storageItem=wrapperBlock.getAttribute('data-storage-item');var lastOpen;try{lastOpen=localStorage.getItem(storageItem)}catch(e){console.log('Your web browser does not support localStorage.')}
if(!lastOpen||wrapperBlock.getAttribute('data-unpublish')){wrapperBlock.style.display='block';setTimeout(function(){wrapperBlock.classList.remove('t658_closed')},500);if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.querySelector('body').classList.add('t658__body_popupshowed')}
if(yesButton){yesButton.addEventListener('click',function(e){wrapperBlock.classList.add('t658_closed');setTimeout(function(){wrapperBlock.style.display='none'},300);if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.querySelector('body').classList.remove('t658__body_popupshowed');try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(e){console.log('Your web browser does not support localStorage.')}
e.preventDefault()})}
if(noButton){noButton.addEventListener('click',function(e){setTimeout(function(){confirmPopup.style.display='none';denyPopup.style.display='block'},300);e.preventDefault()})}}
function t706_onSuccessCallback(){var products=document.querySelector('.t706__cartwin-products');var cartBottom=document.querySelector('.t706__cartwin-bottom');var cartForm=document.querySelector('.t706 .t-form__inputsbox');if(products)t706_slideUp(products,10);if(cartBottom)t706_slideUp(cartBottom,10);if(cartForm)t706_slideUp(cartForm,700);try{tcart__unlockScroll()}catch(error){}}
function t706_slideUp(target,duration){if(!target)return;if(!duration&&duration!==0)duration=500;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}